apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xyla
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xyla
    app.kubernetes.io/part-of: ci10t-786-0003-app
  name: devfile-sample-xyla
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xyla
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xyla
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0003-tenant/ci10t-786-0003-app/devfile-sample-xyla@sha256:163a30d50c06e28821b61cc613c26006a2b2104cc0091f480a23d5e4a6056dbb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
